# Augmented Matrix 

In [22]:
a=input("Enter a number : ")

Enter a number : 53


In [20]:
A1,B1,C1,D1 = input("Enter A1, B1, C1, D1 : ").split()

Enter A1, B1, C1, D1 : 10 4 4 2


In [24]:
print(A1,B1,C1,D1)

10 4 4 2


In [25]:
A2,B2,C2,D2 = input("Enter A2, B2, C2, D2 : ").split()

Enter A2, B2, C2, D2 : 94 22 36 27


In [27]:
print(A2,B2,C2,D2)

94 22 36 27


In [46]:
A = input("Enter A2, B2, C2, D2 : ").split()

Enter A2, B2, C2, D2 : 10 9 6 4 3 7


In [47]:
A

['10', '9', '6', '4', '3', '7']

In [6]:
import numpy as np

In [31]:
A=np.random.randint(100,size=(5,5))
A

array([[57, 23, 39, 75, 31],
       [60, 18, 94, 70,  0],
       [78, 64, 39, 52, 54],
       [ 9, 40, 93, 70, 27],
       [56,  9, 95, 23, 25]])

In [100]:
A[0]

array([32, 38, 96, 76, 32])

In [95]:
B[0][3]

1.0

In [1]:
def Augmented():
    n=(int)(input("Enter the number of equations : "))
    v=(int)(input("Enter the number of variables : "))
    B=np.zeros((n,v+1))
    for i in range(0,n): 
        B[i]=input("Enter coefficients of equation including the constant on RHS : ").split()
    return B

In [77]:
Augmented()

Enter the number of equations : 2
Enter the number of variables : 3
Enter coefficients of equation including the constant on RHS : 10 7 5 7
Enter coefficients of equation including the constant on RHS : 10 7 4 6


array([[10.,  7.,  5.,  7.],
       [10.,  7.,  4.,  6.]])

# Elementary Row Operations

In [ ]:
"""
1. Multiply an equation through by a nonzero constant.
2. Interchange two equations.
3. Add a constant times one equation to another.
Since the rows (horizontal lines) of an augmented matrix correspond to the equations in the associated system,
these three operations correspond to the following operations on the rows of the augmented matrix:
1. Multiply a row through by a nonzero constant.
2. Interchange two rows.
3. Add a constant times one row to another
These are called elementary row operations on a matrix
"""

###  1. Multiply an equation through by a nonzero constant.

In [137]:
n=(input("Enter constant to multiply the row with along with the row number ").split())

Enter constant to multiply the row with along with the row number 10 5


In [138]:
n = list(map(int, n))

In [139]:
n[1]-=1

In [140]:
n

[10, 4]

In [142]:
A

array([[94,  4, 29, 65, 83],
       [39, 93, 87, 35, 78],
       [49, 47, 60, 95, 56],
       [66, 98,  7, 21, 26],
       [24, 86, 28, 97, 71]])

In [7]:
#We can pass a function as a parameter. Don't put brackets for parameters since that will be a function call then use 
#a variable inside the function to get the value of the first function(parameter function)
Elementary(Augmented)

Enter the number of equations : 2
Enter the number of variables : 3
Enter coefficients of equation including the constant on RHS : 10 7 5 2
Enter coefficients of equation including the constant on RHS : 2
Enter constant to multiply the row with along with the row number 10 1


array([[100.,  70.,  50.,  20.],
       [  2.,   2.,   2.,   2.]])

In [4]:
"""
def Elementary(fn):
    A=fn()
    n=(input("Enter constant to multiply the row with along with the row number ").split())
    n = list(map(int, n))
    n[1]-=1
    A[n[1]]*=n[0]
    return A
"""

In [24]:
#Multiply an equation with a non zero constant
def Constant_Multiplication(A):
    n=(input("Enter constant to multiply the row with along with the row number ").split())
    n = list(map(int, n))
    n[1]-=1
    A[n[1]]*=n[0]
    return A

In [25]:
Constant_Multiplication(A)

Enter constant to multiply the row with along with the row number 10 3


array([[ 36,  46,  32,  23,  89],
       [ 22,  65,  53,  99,  37],
       [450, 560, 990, 770, 530],
       [ 18,  24,  15,  47,  80],
       [ 78,  60,  50,  47,  25]])

### 2. Interchange two equations.

Swapping for numpy arrays the usual python way isn't that direct

In [115]:
A[0],A[1]=A[1],A[0]

In [112]:
temp=A[0]
A[0]=A[1]
A[1]=temp 

In [113]:
temp

array([39, 12, 88, 45, 21])

In [122]:
A

array([[39, 93, 87, 35, 78],
       [94,  4, 29, 65, 83],
       [49, 47, 60, 95, 56],
       [66, 98,  7, 21, 26],
       [24, 86, 28, 97, 71]])

In [106]:
x=5
y=6
x,y=y,x

In [107]:
x,y

(6, 5)

In [123]:
A[[0,1]]=A[[1,0]]

In [10]:
A

array([[36, 46, 32, 23, 89],
       [45, 56, 99, 77, 53],
       [22, 65, 53, 99, 37],
       [18, 24, 15, 47, 80],
       [78, 60, 50, 47, 25]])

In [20]:
def Interchange(A):
    n=input("Enter the rows you want to interchange : ").split()
    n=list(map(int,n))
    n = [x - 1 for x in n]
    A[[n[0],n[1]]]=A[[n[1],n[0]]]
    return A

In [26]:
Interchange(A)

Enter the rows you want to interchange : 2 3


array([[ 36,  46,  32,  23,  89],
       [450, 560, 990, 770, 530],
       [ 22,  65,  53,  99,  37],
       [ 18,  24,  15,  47,  80],
       [ 78,  60,  50,  47,  25]])

### 3. Add a constant times one equation to another.

In [33]:
A[0]*A[1]

array([3420,  414, 3666, 5250,    0])

In [37]:
A

array([[657, 203, 979, 775,  31],
       [ 60,  18,  94,  70,   0],
       [ 78,  64,  39,  52,  54],
       [  9,  40,  93,  70,  27],
       [ 56,   9,  95,  23,  25]])

In [39]:
def Equation_Addition(A):
    n=input("Enter C,R1,R2 where R1 <- R1+CR2 Respectively : ").split()
    n=list(map(int,n))
    n = [x - 1 for x in n]
    A[n[1]]=n[0]*A[n[2]]+A[n[1]]
    return A

In [41]:
A=np.ones((5,5))

In [42]:
Equation_Addition(A)

Enter C,R1,R2 where R1 <- R1+CR2 Respectively : 10 1 2


array([[10., 10., 10., 10., 10.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])